#!/usr/bin/env python3
"""Build a standalone single-skill repo from this one.

Two skills here have an audience outside this repo. Ghost writers looking for
`ghost-publish`, and Terragrunt users looking for `terragrunt-skill`, will
never find either inside a personal collection of twenty-odd skills, and the
competing skills for both are standalone. So each gets its own repo for
discoverability -- but a hand-maintained copy would drift, and a drifted copy
is worse than no copy.

So a mirror is a BUILD ARTIFACT. This repo stays the single source of truth,
CI regenerates each mirror on every merge, and nobody edits a mirror by hand.
Issues raised there route back here, which is stated on the generated front
page.

The layout it emits deliberately matches this repo's proven one -- skill in
a subdirectory, `skills` listing `./<skill>` -- because plugin manifests here
fail SILENTLY when the shape is wrong: a marketplace with a bad `source`
registered cleanly and listed zero plugins. Reusing a shape that is known to
install is worth more than a tidier one that is not.

Everything that varies between skills lives in MIRRORS below. Everything else
is shared, so a fix to the build reaches both mirrors at once.

Standard library only. Writes a directory; never touches git or the network.
"""

import argparse
import json
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path

REPO_URL = "https://github.com/kevin-burns/claude-skills"
OWNER = {"name": "Kevin Burns", "url": "https://github.com/kevin-burns"}

# Files copied verbatim from the repo root into the mirror root.
ROOT_FILES = ("LICENSE",)


@dataclass(frozen=True)
class Mirror:
    """Everything that differs between one mirrored skill and the next."""

    skill: str
    # Manifest description. Deliberately NOT read from SKILL.md's frontmatter:
    # that field is tuned for routing and is gated by a separate harness, so
    # borrowing it would couple a published manifest to a value that changes
    # for unrelated reasons.
    description: str
    display_name: str
    # Who the standalone repo exists for. Appears in the generated banner.
    audience: str
    default_prompts: tuple[str, ...]
    # "Productivity" is the value the ghost mirror registered with, so it is
    # the one shape known to install rather than merely to validate.
    category: str = "Productivity"
    # Paths under the skill directory that are local working state rather than
    # part of what a user installs. Relative to the skill root, pruned after
    # the copy so the match is exact rather than by bare directory name.
    exclude: tuple[str, ...] = field(default_factory=tuple)


MIRRORS: dict[str, Mirror] = {
    "ghost-publish": Mirror(
        skill="ghost-publish",
        description=(
            "Publish, update, schedule and verify Ghost posts from a markdown file, driving "
            "TryGhost's official ghst CLI. Strips front matter Ghost would render as prose, and "
            "diffs what Ghost actually stored against the source in both directions."
        ),
        display_name="Ghost Publish",
        audience="Ghost users",
        default_prompts=(
            "Publish this markdown file to my Ghost blog as a draft",
            "Check that the Ghost post matches my source file",
            "Schedule this post for 07:00 tomorrow",
        ),
    ),
    "terragrunt-skill": Mirror(
        skill="terragrunt-skill",
        description=(
            "Generate, validate, review and debug Terragrunt 1.x configurations across AWS, "
            "Azure and GCP. A grep-first reference set that reads the installed terragrunt "
            "version rather than asserting one, with templates for root, stack, unit, catalog "
            "and provider config."
        ),
        display_name="Terragrunt",
        audience="Terragrunt users",
        default_prompts=(
            "Scaffold a Terragrunt layout for dev, staging and prod",
            "Review this terragrunt.hcl against 1.x practice",
            "Diagnose this Terragrunt error",
        ),
        # The eval harness ships; its outputs do not. runs/, arms/ and
        # snapshots/ are regenerated by the harness, hits.jsonl is derived from
        # them, and the tarballs are a local archive -- together 1.7MB of an
        # otherwise 900KB skill, none of which a user installs or reads.
        exclude=(
            "evals/runs",
            "evals/arms",
            # NOT covered by "evals/arms": the on-disk routing arms are a whole second copy
            # of the skill (SKILL.md plus every reference), so a local build shipped the skill
            # twice. Gitignored, so CI never had them and never caught it.
            "evals/arms-disk",
            "evals/snapshots",
            # runs-* covers the cross-model banks AND the dated tarballs. Named
            # individually first, this shipped runs-google-gemini-3.7-flash/ from a local
            # build -- 139 files against the 63 CI published. CI was right only by
            # accident: those paths are gitignored, so the runner never had them.
            "evals/runs-*",
            "evals/hits.jsonl",
            "evals/hits-*.jsonl",
        ),
    ),
}


def banner(m: Mirror) -> str:
    return (
        f"> **This repository is generated.** `{m.skill}` is developed in\n"
        f"> [kevin-burns/claude-skills]({REPO_URL}) and mirrored here on every merge, so that\n"
        f"> {m.audience} can find and install it on its own. **Please raise issues and pull "
        "requests\n"
        f"> [in the source repository]({REPO_URL}/issues)** — changes made here would be "
        "overwritten by\n"
        "> the next build.\n\n"
    )


def build_readme(skill_readme: str, m: Mirror) -> str:
    """The skill's own README, re-pointed for a repo where it is the whole
    project rather than one of twenty-odd."""
    text = skill_readme
    # The in-repo backlink resolves to nothing once the skill is the root
    # project, so it becomes a forward link to the collection instead.
    text = text.replace(
        "Part of [claude-skills](../README.md).",
        f"Part of the [claude-skills]({REPO_URL}) collection, and mirrored here as a "
        "standalone plugin.",
    )
    # The banner is referenced relative to the skill README, which sits one
    # level below the generated front page. Left alone it 404s on the mirror's
    # landing page -- the first thing anyone sees.
    text = text.replace("](images/", f"]({m.skill}/images/")

    # Sibling-skill references are relative paths that only resolve in the
    # source repo. Point them at the collection rather than leaving 404s.
    text = re.sub(
        r"\[`?([a-z0-9-]+)`?\]\(\.\./([a-z0-9-]+)\)",
        rf"[`\1`]({REPO_URL}/tree/main/\2)",
        text,
    )
    title, _, body = text.partition("\n")
    body = body.lstrip()

    # Keep a leading banner image directly under the title. Inserting the
    # generated-repo notice above it pushes the only visual on the landing
    # page below four lines of housekeeping, which is the wrong order for the
    # first thing a stranger sees.
    lead = ""
    if body.startswith("!["):
        image_line, _, rest = body.partition("\n")
        lead, body = image_line + "\n\n", rest.lstrip()

    return f"{title}\n\n{lead}{banner(m)}{body}"


def manifests(version: str, m: Mirror) -> dict[str, dict]:
    """Claude and Codex plugin manifests plus both marketplaces, in the shape
    this repo has verified by installing rather than by validating."""
    homepage = f"https://github.com/kevin-burns/{m.skill}"
    claude_plugin = {
        "name": m.skill,
        "version": version,
        "description": m.description,
        "author": OWNER,
        "homepage": homepage,
        "license": "MIT",
        "skills": [f"./{m.skill}"],
    }
    claude_market = {
        "name": m.skill,
        "description": f"The {m.skill} skill for Claude Code.",
        "owner": OWNER,
        "plugins": [{
            "name": m.skill,
            "source": "./",
            "description": m.description,
            "author": OWNER,
            "homepage": homepage,
            "license": "MIT",
            "category": m.category,
        }],
    }
    codex_plugin = {
        "name": m.skill,
        "version": version,
        "description": m.description,
        "skills": [f"./{m.skill}"],
        "interface": {
            "displayName": m.display_name,
            "category": m.category,
            "defaultPrompt": list(m.default_prompts),
        },
    }
    # Codex marketplaces nest `source` as an object; the bare string Claude
    # uses registers cleanly here and then lists zero plugins.
    agents_market = {
        "name": m.skill,
        "interface": {"displayName": m.display_name},
        "plugins": [{
            "name": m.skill,
            "source": {"source": "local", "path": "./"},
            "policy": {"installation": "AVAILABLE"},
            "category": m.category,
        }],
    }
    return {
        ".claude-plugin/plugin.json": claude_plugin,
        ".claude-plugin/marketplace.json": claude_market,
        ".codex-plugin/plugin.json": codex_plugin,
        ".agents/plugins/marketplace.json": agents_market,
    }


def build(root: Path, out: Path, skill: str = "ghost-publish") -> list[str]:
    try:
        m = MIRRORS[skill]
    except KeyError as e:
        known = ", ".join(sorted(MIRRORS))
        raise SystemExit(f"no mirror configured for {skill!r} -- known: {known}") from e

    src = root / m.skill
    if not (src / "SKILL.md").is_file():
        raise SystemExit(f"no {m.skill}/SKILL.md under {root} -- wrong --root?")

    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    written: list[str] = []
    # The skill itself, minus caches that would otherwise ship to users.
    shutil.copytree(
        src, out / m.skill,
        # .DS_Store is macOS Finder state. It reached a local build and would have reached
        # users from any machine that ran the builder outside CI.
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".pytest_cache", ".venv",
                                      ".DS_Store"),
    )
    # Local working state named by path relative to the skill root, so a future
    # `runs/` elsewhere in a skill is not dropped by accident. Globs are allowed
    # because the banked-run tarballs are named by date and a new bank would
    # otherwise ship.
    for rel in m.exclude:
        for victim in sorted((out / m.skill).glob(rel)):
            if victim.is_dir():
                shutil.rmtree(victim)
            else:
                victim.unlink()
    written += [str(p.relative_to(out)) for p in sorted((out / m.skill).rglob("*")) if p.is_file()]

    for name in ROOT_FILES:
        if (root / name).is_file():
            shutil.copy2(root / name, out / name)
            written.append(name)

    version = json.loads((root / ".claude-plugin/plugin.json").read_text())["version"]
    for path, payload in manifests(version, m).items():
        target = out / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        written.append(path)

    (out / "README.md").write_text(
        build_readme((src / "README.md").read_text(encoding="utf-8"), m), encoding="utf-8")
    written.append("README.md")
    return sorted(written)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.strip().split("\n\n")[0])
    parser.add_argument("--skill", required=True, choices=sorted(MIRRORS),
                        help="which skill to build a standalone repo for")
    parser.add_argument("--root", default=".", help="the claude-skills checkout")
    parser.add_argument("--out", required=True, help="directory to build into (recreated)")
    args = parser.parse_args()

    files = build(Path(args.root).resolve(), Path(args.out).resolve(), args.skill)
    print(f"built {len(files)} files into {args.out}")
    for name in files:
        print(f"  {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
