#!/usr/bin/env python3
"""Keep a "## Contents" list at the top of every long skill reference file.

WHY. Anthropic's Agent Skills best practices: "For reference files longer than
100 lines, include a table of contents at the top. This ensures Claude can see
the full scope of available information even when previewing with partial
reads." Claude may preview a reference with something like `head -100`; a file
whose index is not in that window hides everything below it.

Audited 2026-10-02 (claude-skills-b9nk.1): 32 reference files over 100 lines
had no contents list, the longest 1,735 lines. Hand-written lists go stale the
first time a heading is renamed, so the list is GENERATED and the conventions
check fails when it no longer matches the headings.

SCOPE. `<skill>/references/**/*.md` only. README.md is for humans browsing
GitHub and SKILL.md is the entry point itself; neither is loaded as a
reference.

WHAT IS LISTED. The `##` headings. A file with fewer than three `##` headings
is organised one level down (the interview banks are one `###` per question),
so its `###` headings are listed instead -- provided there are at least three. Headings inside fenced code are
ignored. Anchors follow GitHub's rule, so the links work on GitHub as well as
serving as an index.

    python3 .github/scripts/reference_toc.py          # rewrite lists in place
    python3 .github/scripts/reference_toc.py --check  # exit 1 if any is missing or stale
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
THRESHOLD = 100        # lines; Anthropic's figure, not ours
MARK_START = "<!-- contents: generated by .github/scripts/reference_toc.py; do not edit by hand -->"
MARK_END = "<!-- /contents -->"
BLOCK_RE = re.compile(re.escape(MARK_START) + r".*?" + re.escape(MARK_END) + r"\n?", re.S)
FENCE_RE = re.compile(r"^(```|~~~)")


def reference_files(root=ROOT):
    for skill_md in sorted(root.glob("*/SKILL.md")):
        yield from sorted(skill_md.parent.glob("references/**/*.md"))


def headings(text):
    """(level, title) for ## and ### headings outside fenced code."""
    out, fenced = [], False
    for line in text.splitlines():
        if FENCE_RE.match(line.strip()):
            fenced = not fenced
            continue
        if fenced:
            continue
        m = re.match(r"^(#{2,3})\s+(.+?)\s*#*\s*$", line)
        if m:
            out.append((len(m.group(1)), m.group(2)))
    return out


def anchor(title, seen):
    """GitHub's heading-anchor rule: lowercase, drop punctuation, spaces to hyphens, dedupe."""
    plain = re.sub(r"`|\*\*|__|\[([^\]]*)\]\([^)]*\)", r"\1", title)
    slug = re.sub(r"[^\w\- ]", "", plain.lower()).replace(" ", "-")
    n = seen.get(slug, 0)
    seen[slug] = n + 1
    return slug if n == 0 else f"{slug}-{n}"


def build_block(text):
    body = BLOCK_RE.sub("", text)
    hs = [h for h in headings(body) if h[1].lower() != "contents"]
    h2 = sum(1 for lv, _ in hs if lv == 2)
    h3 = sum(1 for lv, _ in hs if lv == 3)
    level = 3 if h2 < 3 and h3 >= 3 else 2      # one level down only when that is where the structure is
    seen, items = {}, []
    for lv, title in hs:
        a = anchor(title, seen)          # every heading consumes an anchor slot, listed or not
        if lv == level:
            items.append(f"- [{re.sub(r'`', '', title)}](#{a})")
    if not items:
        return None
    return "\n".join([MARK_START, "## Contents", "", *items, MARK_END]) + "\n"


def with_block(text):
    """Text with the generated block in place: replaced if present, else after the H1."""
    block = build_block(text)
    if block is None:
        return text
    if BLOCK_RE.search(text):
        return BLOCK_RE.sub(lambda _: block, text, count=1)
    lines = text.splitlines(keepends=True)
    at = 0
    for i, line in enumerate(lines[:10]):
        if line.startswith("# "):
            at = i + 1
            break
    return "".join(lines[:at]) + ("\n" if at else "") + block + "\n" + "".join(lines[at:]).lstrip("\n")


def needs_block(text):
    return text.count("\n") > THRESHOLD


def problems(root=ROOT):
    """(path, reason) for every long reference file whose contents list is missing or stale."""
    out = []
    for path in reference_files(root):
        text = path.read_text(encoding="utf-8")
        if not needs_block(text):
            continue
        if not BLOCK_RE.search(text):
            out.append((path, "over 100 lines with no generated contents list"))
        elif with_block(text) != text:
            out.append((path, "contents list is stale; headings have changed"))
    return out


def main(argv):
    if "--check" in argv:
        bad = problems()
        for path, why in bad:
            print(f"{path.relative_to(ROOT)}: {why}")
        ok = "all long reference files have a current contents list"
        print(f"{len(bad)} reference file(s) need a contents list" if bad else ok)
        return 1 if bad else 0
    changed = 0
    for path in reference_files():
        text = path.read_text(encoding="utf-8")
        if needs_block(text):
            new = with_block(text)
            if new != text:
                path.write_text(new, encoding="utf-8")
                changed += 1
                print(f"wrote {path.relative_to(ROOT)}")
    print(f"{changed} file(s) updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
