"""Tests for the standalone-skill mirror builder.

A mirror is what strangers install, so a bad build reaches users directly
rather than being caught in review. These check the things that would ship
broken silently: manifest shapes, relative links that only resolve in the
source repo, caches leaking into a published tree, and -- since the builder
went from one skill to several -- a value belonging to one mirror turning up
in another.
"""

import json
import re
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

from build_skill_mirror import MIRRORS, build, build_readme, manifests  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
SKILLS = sorted(MIRRORS)


@pytest.mark.parametrize("skill", SKILLS)
def test_build_emits_the_skill_and_all_four_manifests(tmp_path, skill):
    files = build(ROOT, tmp_path / "out", skill)
    for expected in (
        f"{skill}/SKILL.md",
        f"{skill}/README.md",
        ".claude-plugin/plugin.json",
        ".claude-plugin/marketplace.json",
        ".codex-plugin/plugin.json",
        ".agents/plugins/marketplace.json",
        "README.md",
        "LICENSE",
    ):
        assert expected in files, f"{expected} missing from the {skill} mirror"


def test_ghost_ships_its_scripts(tmp_path):
    files = build(ROOT, tmp_path / "out", "ghost-publish")
    assert "ghost-publish/scripts/verify_post.py" in files
    assert "ghost-publish/scripts/prepare_post.py" in files


def test_terragrunt_ships_its_references_and_the_eval_harness(tmp_path):
    """The references ARE the skill -- it is a router that reads them -- and
    RESULTS.md is the only published evidence that the policy does anything."""
    files = build(ROOT, tmp_path / "out", "terragrunt-skill")
    for expected in (
        "terragrunt-skill/references/hcl-blocks.md",
        "terragrunt-skill/references/error-patterns.md",
        "terragrunt-skill/references/cicd.md",
        "terragrunt-skill/scripts/scan_pre10.py",
        "terragrunt-skill/evals/RESULTS.md",
        "terragrunt-skill/evals/grade.py",
    ):
        assert expected in files, f"{expected} missing from the terragrunt mirror"


def test_terragrunt_leaves_local_eval_state_behind(tmp_path):
    """runs/, arms/ and snapshots/ are regenerated by the harness and the
    tarballs are a local archive -- 1.7MB that nobody installing the skill
    reads. Shipping them once sets the expectation that they stay current."""
    files = build(ROOT, tmp_path / "out", "terragrunt-skill")
    for name in files:
        assert "/evals/runs/" not in name
        assert "/evals/arms/" not in name
        assert "/evals/snapshots/" not in name
        assert not name.endswith(".tar.gz")
        assert not name.endswith("hits.jsonl")


@pytest.mark.parametrize("skill", SKILLS)
def test_manifests_keep_the_shapes_this_repo_verified_by_installing(tmp_path, skill):
    """Plugin manifests fail silently when the shape is wrong -- a bad
    marketplace `source` registered cleanly and then listed zero plugins.
    These assertions pin the shapes that are known to install."""
    out = tmp_path / "out"
    build(ROOT, out, skill)

    claude = json.loads((out / ".claude-plugin/plugin.json").read_text())
    assert claude["skills"] == [f"./{skill}"], "skills must list a subdirectory path"

    # Claude's marketplace takes a bare string source; Codex's nests an object.
    market = json.loads((out / ".claude-plugin/marketplace.json").read_text())
    assert market["plugins"][0]["source"] == "./"

    agents = json.loads((out / ".agents/plugins/marketplace.json").read_text())
    assert agents["plugins"][0]["source"] == {"source": "local", "path": "./"}


@pytest.mark.parametrize("skill", SKILLS)
def test_no_manifest_carries_another_mirrors_name(tmp_path, skill):
    """The failure this refactor could introduce: one skill's identity left
    hardcoded and shipped inside another's manifests. It broke nothing
    visible when both were ghost-publish."""
    out = tmp_path / "out"
    build(ROOT, out, skill)
    others = [s for s in SKILLS if s != skill]
    for path in (
        ".claude-plugin/plugin.json",
        ".claude-plugin/marketplace.json",
        ".codex-plugin/plugin.json",
        ".agents/plugins/marketplace.json",
    ):
        text = (out / path).read_text()
        for other in others:
            assert other not in text, f"{path} in the {skill} mirror mentions {other}"


@pytest.mark.parametrize("skill", SKILLS)
def test_no_relative_link_in_the_mirror_points_at_nothing(tmp_path, skill):
    """The mirror carries TWO copies of the skill README: the generated front page, whose
    links build_readme rewrites, and <skill>/README.md, which is copied VERBATIM. SKILL.md and
    every reference are verbatim too. So a `](../other-skill)` link -- fine in a collection of
    twenty-odd -- resolves to a path that does not exist once the skill is the whole repo, and
    it is invisible until a stranger clicks it.

    Resolving every relative link against the built tree needs no allowlist: `../README.md`
    from <skill>/README.md lands on the generated front page and passes, while `../c7search`
    lands on nothing and fails. That distinction is the whole check."""
    out = tmp_path / "out"
    build(ROOT, out, skill)
    dead = []
    for md in sorted(out.rglob("*.md")):
        # Strip fenced blocks and inline code first. `![alt](url)` in ghost-publish/SKILL.md is
        # markdown SYNTAX being documented, not a link, and reading it as one made this check
        # fail on prose that was never wrong.
        text = re.sub(r"^```.*?^```", "", md.read_text(encoding="utf-8"), flags=re.S | re.M)
        text = re.sub(r"`[^`\n]*`", "", text)
        for target in re.findall(r"\]\(([^)\s#]+)\)", text):
            if re.match(r"[a-z][a-z0-9+.-]*:", target) or target.startswith("#"):
                continue          # absolute URL, or an in-page anchor
            if not (md.parent / target).exists():
                dead.append(f"{md.relative_to(out)} -> {target}")
    assert not dead, "relative links resolving to nothing in the mirror:\n  " + "\n  ".join(dead)


@pytest.mark.parametrize("skill", SKILLS)
def test_no_caches_or_virtualenvs_reach_the_published_tree(tmp_path, skill):
    files = build(ROOT, tmp_path / "out", skill)
    for name in files:
        assert "__pycache__" not in name
        assert not name.endswith(".pyc")
        assert ".venv" not in name
        assert ".pytest_cache" not in name


def test_an_unconfigured_skill_is_refused_rather_than_half_built(tmp_path):
    with pytest.raises(SystemExit) as e:
        build(ROOT, tmp_path / "out", "clear-and-human")
    assert "no mirror configured" in str(e.value)


@pytest.mark.parametrize("skill", SKILLS)
def test_readme_rewrites_the_backlink_that_would_404(tmp_path, skill):
    """`Part of [claude-skills](../README.md)` resolves inside this repo. The
    generated front page has to point at the collection instead."""
    out = build_readme(f"# {skill}\n\nPart of [claude-skills](../README.md).\n", MIRRORS[skill])
    assert "../README.md" not in out
    assert "github.com/kevin-burns/claude-skills" in out


@pytest.mark.parametrize("skill", SKILLS)
def test_the_real_readme_has_no_backlink_left_unrewritten(tmp_path, skill):
    """The rewrite above is a string match against the source README. If that
    line is ever reworded, the match silently stops firing and the mirror's
    landing page ships a link that 404s."""
    out = tmp_path / "out"
    build(ROOT, out, skill)
    assert "(../README.md)" not in (out / "README.md").read_text()


@pytest.mark.parametrize("skill", SKILLS)
def test_readme_says_where_issues_go_and_who_for(tmp_path, skill):
    """A stranger's first instinct is to open an issue where they found the
    code. The banner has to redirect that before they do -- and it names the
    audience, so a wrong audience is a wrong banner rather than a no-op."""
    m = MIRRORS[skill]
    out = build_readme(f"# {skill}\n\nBody.\n", m)
    assert "generated" in out.lower()
    assert "/issues" in out
    assert m.audience in out
    assert out.startswith(f"# {skill}")  # title stays first, banner follows


def test_sibling_skill_links_are_rewritten_to_the_collection():
    out = build_readme(
        "# x\n\nUse [`clear-and-human`](../clear-and-human) for prose.\n",
        MIRRORS["ghost-publish"],
    )
    assert "(../clear-and-human)" not in out
    assert "claude-skills/tree/main/clear-and-human" in out


@pytest.mark.parametrize("skill", SKILLS)
def test_version_is_taken_from_the_source_manifest(skill):
    source_version = json.loads((ROOT / ".claude-plugin/plugin.json").read_text())["version"]
    built = manifests(source_version, MIRRORS[skill])
    assert built[".claude-plugin/plugin.json"]["version"] == source_version
    assert built[".codex-plugin/plugin.json"]["version"] == source_version


@pytest.mark.parametrize("skill", SKILLS)
def test_rebuild_is_deterministic(tmp_path, skill):
    """CI diffs the built tree against the mirror to decide whether to push.
    A build that varies run to run would commit noise forever."""
    first = build(ROOT, tmp_path / "a", skill)
    second = build(ROOT, tmp_path / "b", skill)
    assert first == second
    for name in first:
        assert (tmp_path / "a" / name).read_bytes() == (tmp_path / "b" / name).read_bytes()


def test_banner_path_is_rewritten_for_the_generated_front_page():
    """The skill README references the banner relatively, and that README sits
    one level below the mirror's generated landing page. Left alone the image
    404s on the first thing anyone sees."""
    out = build_readme(
        "# ghost-publish\n\n![banner](images/banner.webp)\n\nBody.\n",
        MIRRORS["ghost-publish"],
    )
    assert "](ghost-publish/images/banner.webp)" in out
    assert "](images/banner.webp)" not in out


def test_banner_sits_above_the_generated_notice():
    """Order matters on a landing page: title, then the one visual, then the
    housekeeping. Notice first buries the banner under four lines of prose."""
    out = build_readme(
        "# ghost-publish\n\n![b](images/banner.webp)\n\nBody text here.\n",
        MIRRORS["ghost-publish"],
    )
    lines = out.splitlines()
    assert lines[0].startswith("# ")
    assert lines[2].startswith("!["), "banner must be directly under the title"
    assert out.index("![") < out.index("This repository is generated")


@pytest.mark.parametrize("skill", SKILLS)
def test_every_image_the_front_page_references_is_actually_published(tmp_path, skill):
    """Shipping the reference without the file is worse than neither, and it is
    invisible until someone loads the mirror's landing page. Checks whatever the
    README actually links to rather than one hardcoded filename, so a second
    image added later is covered without anyone remembering to."""
    out = tmp_path / "out"
    files = set(build(ROOT, out, skill))
    referenced = re.findall(rf"\]\({re.escape(skill)}/(images/[^)\s]+)\)",
                            (out / "README.md").read_text())
    assert referenced, f"the {skill} front page references no image at all"
    for rel in referenced:
        assert f"{skill}/{rel}" in files, f"{skill}/{rel} is linked but was not published"


# --------------------------------------------------------------------- the workflows

REPO_ROOT = ROOT
WORKFLOWS = REPO_ROOT / ".github" / "workflows"


@pytest.mark.parametrize("skill", SKILLS)
def test_every_mirror_scans_the_built_tree_before_it_pushes(skill):
    """The source repo is scanned twice, and neither covers this push. ci.yml and the mirror
    workflows both fire on push to main IN PARALLEL, so nothing makes a mirror wait for the
    secrets job -- a secret on main can reach a second public repo before the first reports.
    And the four plugin manifests are synthesised by the builder, so they have never been in
    claude-skills and a full-history scan of it cannot see them."""
    wf = WORKFLOWS / f"mirror-{skill}.yml"
    text = wf.read_text()
    assert "gitleaks dir" in text, f"{wf.name} pushes without scanning the built tree"
    scan = text.index("gitleaks dir")
    push = text.index("Push to ${{ env.TARGET_REPO }}")
    assert scan < push, f"{wf.name} scans AFTER pushing, which is not a gate"
    assert "--redact" in text, "a finding must not print the secret into a public build log"


def test_every_gitleaks_pin_in_the_repo_agrees():
    """Four files now pin a gitleaks version: the pre-commit hook, ci.yml, and both mirror
    workflows. A version pinned in four places is three chances to drift, which is the shape
    this repo spent a week removing from terragrunt-skill. This is the thing that enforces it."""
    sources = {
        ".pre-commit-config.yaml": r"gitleaks\n\s+rev: v([\d.]+)",
        ".github/workflows/ci.yml": r"GITLEAKS_VERSION: ([\d.]+)",
    }
    for skill in SKILLS:
        sources[f".github/workflows/mirror-{skill}.yml"] = r"GITLEAKS_VERSION: ([\d.]+)"

    found = {}
    for rel, pattern in sources.items():
        text = (REPO_ROOT / rel).read_text()
        m = re.search(pattern, text)
        assert m, f"no gitleaks version pin found in {rel}"
        found[rel] = m.group(1)
    assert len(set(found.values())) == 1, f"gitleaks pins disagree: {found}"
